on:
  release:
    types:
      - created

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
jobs:
  action:
        uses: jjerhub/Utilities.GithubActions/ZipContents.yml@master
        with:
          name: 'ADRFDR_Extended'
