name: Do zip on release
on:
  release:
    types:
      - published
  workflow_dispatch:
      
jobs:
  do_zip:
    secrets: inherit
    uses: jjerhub/Utilities.GithubActions/.github/workflows/ZipContents.yml@master
    with:
      zip-file-name: 'ADRFDR_Extended'
